### PR TITLE
Add support for different JVM languages - see issue #28

### PR DESCRIPTION
**Pull request by skirge**
Support for extending sonar-findbugs plugins with language specific plugins. 
See https://github.com/skirge/findsecbugsscala for example, only this plugin needs dependency on sonar-scala plugin (changes are pending on sonar-scala to be able to compile). 
Tested on Sonarqube 6.5 with Scala and Java projects, sbt and Maven builds.

### CODE REVIEW

**Comment by h3xstream** [comment]
Is it possible because of new API?

I have not look deeply at the changeset..

 - Those it allows the reuse of rules for multiple languages ? This used to be a big limitation..
 - Will it migrate seamlessly existing rules and profiles.

**Comment by skirge** [comment]
No, the API version is left at version 5.6. I used the idea of plugin extending other plugin (BasePlugin) and changes here were needed to register some settings which were hardcoded (supported extensions and languages etc.). Seems that nothing was broken in the process. Downside is that Findbugs is run twice (when other language is detected).

**Comment by skirge** [comment]
No, the API version is left at version 5.6. I used the idea of plugin extending other plugin (BasePlugin) and changes here were needed to register some settings which were hardcoded (supported extensions and languages etc.). Seems that nothing was broken in the process. Downside is that Findbugs is run twice (when other language is detected).

**Comment by h3xstream** [comment]
Mini update : 
I ran the plugin with your change on 6 type test projects (part of my integration tests).

The only project that had issue was one with JSP files. Based on the stacktrace it seems to be unrelated to your changes.
```
[WARNING] An error occurs while processing the bug instance [BugInstance type=SPP_EQUALS_ON_ENUM, class=org.apache.jsp.xss.xss5_jsp, line=97]
java.lang.NullPointerException: null
        at org.sonar.plugins.findbugs.resource.SmapParser.getSmapLocation(SmapParser.java:168)
        at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.getJspLineNumberFromSmap(ByteCodeResourceLocator.java:200)
        at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.extractSmapLocation(ByteCodeResourceLocator.java:168)
        at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:159)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
```

**Comment by h3xstream** [comment]
```
  Cannot open codebase filesystem:{...]\sonar-findbugs-testrepo\java-web-jsp\src\main\webapp\xss\xss5.jsp
    java.io.IOException: Wrong magic bytes of 3c254074 for zip file [...]\sonar-findbugs-testrepo\java-web-jsp\src\main\webapp\xss\xss5.jsp of 331 bytes
      At edu.umd.cs.findbugs.classfile.impl.ZipFileCodeBase.<init>(ZipFileCodeBase.java:87)
      At edu.umd.cs.findbugs.classfile.impl.ZipCodeBaseFactory.makeZipCodeBase(ZipCodeBaseFactory.java:39)
```

**Comment by skirge** [comment]
Maybe it's caused by this code in FindbugsConfiguration:
{code}
for (File file : getSourceFiles()) { //The original source file are look at by some detectors
      if("java".equals(FilenameUtils.getExtension(file.getName()))) {
        findbugsProject.addFile(file.getCanonicalPath());
      }
    }
{code}

It seems that Findbugs/Spotbugs ignores ".java" files internally: spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/impl/ClassPathBuilder.java in processWorkList method:
{code}
// Detect .java files, which are probably human error
            if (item.getCodeBaseLocator() instanceof FilesystemCodeBaseLocator) {
                FilesystemCodeBaseLocator l = (FilesystemCodeBaseLocator) item.getCodeBaseLocator();
                if (l.getPathName().endsWith(".java")) {
                    if (DEBUG){
                        System.err.println("Ignoring .java file \"" + l.getPathName() + "\" specified in classpath or auxclasspath");
                    }
                    continue;
                }
            }
{code} but not other files.

**Comment by h3xstream** [comment]
@skirge Good catch!

**Comment by h3xstream** [comment]
Still doing some testing.. But this change seems to be a good for long term.

**Pull request merged**
