### PR TITLE
Feature: JSP support

### PR DESCRIPTION
**Pull request by h3xstream**
This changeset introduce the support for the analysis of JSP by FindBugs. This will have multiple benefits including the discovery of XSS.
This is also the first step in order to support alternative language such as Groovy, Scala and other their template languages similar to JSP.

EDIT: The initial implementation was revised. None of the issues previously mentions are still applying.

### CODE REVIEW

**Comment by benzonico** [comment]
Hi @h3xstream ,

Thanks for the contribution. We will review it during next sprint on findbugs plugin which is not likely to happen until 2016 now. 

Thanks.

**Comment by h3xstream** [comment]
@benzonico Any ETA?

**Comment by benzonico** [comment]
@h3xstream I contacted you by email about this.

**Comment by ganncamp** [comment]
Hi @h3xstream. This plugin has been officially moved into the SonarQubeCommunity organization, meaning that SonarSource is no longer actively maintaining it. So, at least on our side, there won't be a "next sprint".

Since you clearly have an interest in this plugin, would you be interested in becoming a/the maintainer?

**Comment by h3xstream** [comment]
The build is expected to pass with the simplify build.

Assuming the build passed,
I will do some tests with the latest integration to make sure. The language does not cause any issue.

**Pull request merged**
