### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by VinodAnandan**
- find-sec-bugs (1.7.1)
- sslr-core (1.22)
- annotations (3.0.1u2)
- spotbugs (3.1.0-RC5)
- mockito-core ( 2.8.47)
- maven-compiler-plugin (3.6.2)
- sonar-packaging-maven-plugin (1.18.0.372)
- maven-enforcer-plugin (3.0.0-M1)

### CODE REVIEW

**Comment by h3xstream** [comment]
What version of SonarQube did you test?

**Comment by VinodAnandan** [comment]
Hi Philippe,

I have installed the sonar-findbugs plugin with the latest OWASP Sonarqube docker image which contains Sonarqube 6.5 and the latest Java plugin. But I noticed that sonar-findbugs has compatibility issues if Sonarqube has an older Java plugin version.  Also, the scanning breaks because of the guava version compatibility, so I have changed them to the older version.

Thanks,

Vinod

**Comment by h3xstream** [comment]
Thanks

**Comment by h3xstream** [comment]
Please note that updating version from dependencies add little value to the project. The descriptions and profiles need to be updated to include new rules.

**Comment by Thg-vinod-anandan** [comment]
Hi Philippe,

Thank you for the information. I will do this, could you please let me know where I can find the new rules list? 

Thank you,

Vinod

**Comment by h3xstream** [comment]
Yep No problem. It is not fully obvious their is this step required.

The script and instruction to generate the profiles/rules:
https://github.com/SonarQubeCommunity/sonar-findbugs/tree/master/generate_profiles

**Pull request merged**
